<?php
require_once __DIR__ . '/../../session-bridge.php';
// Check role
if ($_SESSION['user_role'] !== 'municipal' && !str_ends_with($_SESSION['user_role'], '_mto')) {
    header('Location: ../../login.php');
    exit;
}

$pageTitle = 'Municipal Reports';

ob_start();
?>
    <h2 class="section-title">Reports Management</h2>

    <!-- Report Generator -->
    <div class="card" style="margin-bottom:16px;">
        <div class="card-header">
            <h3 class="card-title"><i class="fas fa-file-alt"></i> Generate Report</h3>
        </div>
        <div class="card-body">
            <form style="display:grid; grid-template-columns:repeat(2,1fr); gap:16px;">
                <div class="lupto-form-group">
                    <label>Report Type</label>
                    <select class="filter-select" style="width:100%;">
                        <option>Tourist Spot Report</option>
                        <option>Municipality Report</option>
                        <option>Transportation Report</option>
                        <option>Approval Report</option>
                    </select>
                </div>
                <div class="lupto-form-group">
                    <label>Date Range</label>
                    <input type="date" class="filter-select" style="width:100%;">
                </div>
                <div class="lupto-form-group">
                    <label>Municipality (Optional)</label>
                    <select class="filter-select" style="width:100%;">
                        <option>All Municipalities</option>
                        <option>San Fernando City</option>
                        <option>San Juan</option>
                    </select>
                </div>
                <div class="lupto-form-group">
                    <label>Export Format</label>
                    <select class="filter-select" style="width:100%;">
                        <option>PDF</option>
                        <option>Excel</option>
                        <option>CSV</option>
                    </select>
                </div>
                <div style="grid-column:1/-1;">
                    <button type="button" class="btn-gov">
                        <i class="fas fa-download"></i> Generate Report
                    </button>
                </div>
            </form>
        </div>
    </div>

    <!-- Recent Reports -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><i class="fas fa-history"></i> Recent Reports</h3>
        </div>
        <div class="card-body" style="padding:0;">
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Report Name</th>
                        <th>Type</th>
                        <th>Date Generated</th>
                        <th>Generated By</th>
                        <th>Format</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><i class="fas fa-file-pdf" style="color:#ff0000;"></i> June_2026_Tourist_Spot_Report.pdf</td>
                        <td>Tourist Spot Report</td>
                        <td><?= date('M d, Y h:i A') ?></td>
                        <td>Municipal Admin</td>
                        <td>PDF</td>
                        <td>
                            <button class="btn-gov btn-gov-secondary" style="padding:4px 8px; font-size:11px;">
                                <i class="fas fa-download"></i> Download
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td><i class="fas fa-file-excel" style="color:#217346;"></i> May_2026_Municipality_Report.xlsx</td>
                        <td>Municipality Report</td>
                        <td><?= date('M d, Y', strtotime('-1 month')) ?></td>
                        <td>Municipal Admin</td>
                        <td>Excel</td>
                        <td>
                            <button class="btn-gov btn-gov-secondary" style="padding:4px 8px; font-size:11px;">
                                <i class="fas fa-download"></i> Download
                            </button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
<?php
$pageContent = ob_get_clean();
if (is_ajax_request()) {
    if (isset($extraHeadContent)) {
        echo $extraHeadContent;
    }
    echo $pageContent;
    exit;
}
include '../../components/sections.php';
