<?php

namespace Database\Seeders;

use App\Models\Municipality;
use App\Models\TouristSpot;
use Illuminate\Database\Seeder;

class TouristSpotSeeder extends Seeder
{
    public function run(): void
    {
        $munis = Municipality::all();

        $spots = [
            [
                'name' => 'Urbiztondo Surfing Beach',
                'category' => 'Beach',
                'classification_status' => 'EXIST',
                'entrance_fee' => 0,
                'rating' => 4.8,
                'visits' => 12450,
                'description' => 'The famous surfing capital of Northern Luzon with world-class waves, beach bars, and cafes.',
                'latitude' => 16.6698,
                'longitude' => 120.3204,
                'opening_time' => '05:00',
                'closing_time' => '22:00',
                'is_maintenance' => false,
                'status' => 'approved',
                'municipality_id' => $munis->firstWhere('name', 'San Juan')?->id ?? 1,
            ],
            [
                'name' => 'Tangadan Falls',
                'category' => 'Waterfalls',
                'classification_status' => 'EXIST',
                'entrance_fee' => 50,
                'rating' => 4.7,
                'visits' => 8900,
                'description' => 'A magnificent multi-tier waterfall surrounded by lush green forests and cold cliff-diving pools.',
                'latitude' => 16.6680,
                'longitude' => 120.4430,
                'opening_time' => '07:30',
                'closing_time' => '17:00',
                'is_maintenance' => false,
                'status' => 'approved',
                'municipality_id' => $munis->firstWhere('name', 'San Gabriel')?->id ?? 1,
            ],
            [
                'name' => 'Ma-Cho Taoist Temple',
                'category' => 'Historical',
                'classification_status' => 'EXIST',
                'entrance_fee' => 0,
                'rating' => 4.6,
                'visits' => 6400,
                'description' => 'A grand Taoist temple perched on a hill overlooking the South China Sea, built in 1975.',
                'latitude' => 16.6200,
                'longitude' => 120.3167,
                'opening_time' => '07:00',
                'closing_time' => '17:30',
                'is_maintenance' => false,
                'status' => 'approved',
                'municipality_id' => $munis->firstWhere('name', 'San Fernando')?->id ?? 1,
            ],
            [
                'name' => 'Baluarte Watchtower',
                'category' => 'Historical',
                'classification_status' => 'EXIST',
                'entrance_fee' => 20,
                'rating' => 4.5,
                'visits' => 5100,
                'description' => 'A restored 400-year-old Spanish fortress tower standing along the coastline of Luna.',
                'latitude' => 16.8520,
                'longitude' => 120.3700,
                'opening_time' => '06:00',
                'closing_time' => '18:00',
                'is_maintenance' => false,
                'status' => 'approved',
                'municipality_id' => $munis->firstWhere('name', 'Luna')?->id ?? 1,
            ],
            [
                'name' => 'Luna Pebble Beach',
                'category' => 'Beach',
                'classification_status' => 'EMERGE',
                'entrance_fee' => 0,
                'rating' => 4.4,
                'visits' => 4300,
                'description' => 'A unique coastline covered in smooth, colorful pebbles instead of traditional sand.',
                'latitude' => 16.8540,
                'longitude' => 120.3720,
                'opening_time' => '06:00',
                'closing_time' => '18:00',
                'is_maintenance' => false,
                'status' => 'approved',
                'municipality_id' => $munis->firstWhere('name', 'Luna')?->id ?? 1,
            ],
            [
                'name' => 'Bauang Grape Farms',
                'category' => 'Ecotourism',
                'classification_status' => 'EXIST',
                'entrance_fee' => 30,
                'rating' => 4.6,
                'visits' => 7800,
                'description' => 'Pick-your-own fresh grapes straight from lush vineyards and taste local grape wines.',
                'latitude' => 16.5180,
                'longitude' => 120.3400,
                'opening_time' => '08:00',
                'closing_time' => '17:00',
                'is_maintenance' => false,
                'status' => 'approved',
                'municipality_id' => $munis->firstWhere('name', 'Bauang')?->id ?? 1,
            ],
            [
                'name' => 'Christ the Redeemer Shrine',
                'category' => 'Religious',
                'classification_status' => 'POTENTIAL',
                'entrance_fee' => 0,
                'rating' => 4.5,
                'visits' => 3900,
                'description' => 'A majestic statue of Christ overlooking the city of San Fernando and La Union coastline.',
                'latitude' => 16.6110,
                'longitude' => 120.3200,
                'opening_time' => '06:00',
                'closing_time' => '18:00',
                'is_maintenance' => false,
                'status' => 'approved',
                'municipality_id' => $munis->firstWhere('name', 'San Fernando')?->id ?? 1,
            ],
            [
                'name' => 'Agoo Eco-Fun Park',
                'category' => 'Ecotourism',
                'classification_status' => 'EMERGE',
                'entrance_fee' => 15,
                'rating' => 4.3,
                'visits' => 3200,
                'description' => 'A serene pine-tree park by the beach perfect for picnics, camping, and sunset watching.',
                'latitude' => 16.3200,
                'longitude' => 120.3550,
                'opening_time' => '07:00',
                'closing_time' => '18:00',
                'is_maintenance' => false,
                'status' => 'approved',
                'municipality_id' => $munis->firstWhere('name', 'Agoo')?->id ?? 1,
            ],
            [
                'name' => 'Poro Point Baywalk',
                'category' => 'Park',
                'classification_status' => 'EXIST',
                'entrance_fee' => 0,
                'rating' => 4.5,
                'visits' => 5800,
                'description' => 'A scenic boardwalk and lighthouse park along San Fernando Bay, ideal for jogging and biking.',
                'latitude' => 16.6180,
                'longitude' => 120.2920,
                'opening_time' => '05:00',
                'closing_time' => '21:00',
                'is_maintenance' => false,
                'status' => 'approved',
                'municipality_id' => $munis->firstWhere('name', 'San Fernando')?->id ?? 1,
            ],
        ];

        foreach ($spots as $spot) {
            TouristSpot::updateOrCreate(['name' => $spot['name']], $spot);
        }
    }
}
